#!/usr/bin/env bash
# Script to get subdomains details

display_info () {
    domain="$1"
    subdomain="$2"
    result=$(dig +short "$subdomain.$domain" | tail -n1)
    if [[ -n "$result" ]]; then
        echo "The subdomain $subdomain is an A record and points to $result"
    else
        echo "The subdomain $subdomain does not resolve to an IP address."
    fi
}

if [ -z "$1" ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

if [ -n "$subdomain" ]; then
    display_info "$domain" "$subdomain"
else
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        display_info "$domain" "$subdomain"
    done
fi

